services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  image: docker:stable
  script:
    - docker build -t $IMAGE_TAG:latest .
    - docker push $IMAGE_TAG:latest

